# Register at https://openweathermap.org to get your API key
api_key = "54ff6e571935cdc004adad3a62a56258"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "5128581"

# Display settings
units = "metric"
display_symbol = "°C"
